(* ADVENTURE-STYLE GAME *)
(* AUTHOR : NICK GAMMON *)

PROGRAM ADVENTURE;
CONST
  HOME = CHR(10);
  CR = CHR(10);

  INHAND     = -1;
  MAXOBJ     = 6;
  MAXWORDS   = 2;
  MAXCARRY   = 3;
  MAXLINE    = 80;
  LENGH_NORM = 3;

  CARRIED    = -1;
  NOTCARRIED = 2;
  NEARBY     = 3;

  (*OBJECTS *)
  LAMP       = 1;
  BUN        = 2;
  ROD        = 3;
  RING       = 4;
  STATUE     = 5;
  CROWN      = 6;

VAR
  LINE : STRING[MAXLINE];
  OBJECTS : ARRAY [1..MAXOBJ] OF INTEGER;
  WRD : ARRAY [1..2] OF STRING;
  STARTWORD, ENDWORD : ARRAY [1..MAXWORDS] OF INTEGER;
  HOLDING, SCORE, TURNS, OBJ, PTR, ROOM, OLDROOM : INTEGER;


FUNCTION CARRYING (X : INTEGER) : BOOLEAN;
BEGIN
  IF OBJECTS[X] = INHAND THEN
    CARRYING := TRUE
  ELSE
    CARRYING := FALSE
END;


FUNCTION INROOM (X : INTEGER) : BOOLEAN;
BEGIN
  IF OBJECTS[X] = ROOM THEN
    INROOM := TRUE
  ELSE
    INROOM := FALSE
END;


FUNCTION HERE (X : INTEGER) : BOOLEAN;
BEGIN
  HERE := CARRYING(X) OR INROOM(X)
END;


FUNCTION SAYWORD (X : INTEGER) : CHAR;
  VAR I : INTEGER;
BEGIN
  FOR I := STARTWORD[X] TO ENDWORD[X] DO
    WRITE (LINE[I]);

  SAYWORD := CHR(0);
END;


FUNCTION CONVERTOBJECT : INTEGER;
BEGIN
  OBJ := 0;
  IF WRD[2] = '' THEN
  BEGIN
    WRITE (SAYWORD(1),' WHAT?',CR)
  END
  ELSE
  BEGIN
    IF WRD[2] = 'LAM' THEN
	  OBJ := LAMP
	ELSE IF (WRD[2] = 'BUN')  OR (WRD[2] = 'CRE') THEN
	  OBJ := BUN
	ELSE IF WRD[2] = 'ROD' THEN
	  OBJ := ROD
	ELSE IF (WRD[2] = 'RIN')  OR (WRD[2] = 'GOL') THEN
	  OBJ := RING
	ELSE IF (WRD[2] = 'SIL')  OR (WRD[2] = 'STA') THEN
	  OBJ := STATUE
	ELSE IF (WRD[2] = 'JEW')  OR (WRD[2] = 'CRO') THEN
	  OBJ := CROWN
	ELSE
	  OBJ := -1
  END;

  CONVERTOBJECT := OBJ
END;


FUNCTION DESCRIBEOBJECT (X : INTEGER) : CHAR;
BEGIN
  CASE X OF
    LAMP:   WRITE ('LAMP');
    BUN:    WRITE ('CREAM BUN');
    ROD:    WRITE ('ROD');
    RING:   WRITE ('GOLD RING');
    STATUE: WRITE ('SILVER STATUE');
    CROWN:  WRITE ('JEWELLED CROWN')
  END;
  DESCRIBEOBJECT := CHR(0)
END;


FUNCTION GETOBJECT (MUSTBE : INTEGER) : BOOLEAN;
BEGIN
  GETOBJECT := FALSE;
  IF CONVERTOBJECT > 0 THEN
  BEGIN
    IF NOT HERE(OBJ) THEN
      WRITE ('I SEE NO ',SAYWORD(2),' HERE.',CR)
    ELSE
      CASE MUSTBE OF
        CARRIED:
          IF CARRYING(OBJ) THEN
            GETOBJECT := TRUE
          ELSE
            WRITE ('YOU''RE NOT CARRYING IT!',CR);
        NOTCARRIED:
          IF NOT CARRYING(OBJ) THEN
            GETOBJECT := TRUE
          ELSE
            WRITE ('YOU''RE ALREADY CARRYING IT!',CR)
      ELSE
        GETOBJECT := TRUE
      END
  END
  ELSE
    WRITE('I DON''T UNDERSTAND ',SAYWORD(2),' !',CR)
END;


PROCEDURE PICKUP (X : INTEGER);
BEGIN
  IF HOLDING >= MAXCARRY THEN
    WRITE ('YOU CAN''T CARRY ANY MORE!',CR)
  ELSE
  BEGIN
    HOLDING := HOLDING + 1;
    OBJECTS[X] := INHAND;
    WRITE ('TAKEN.',CR)
  END
END;


PROCEDURE DROPIT (X : INTEGER);
BEGIN
  HOLDING := HOLDING - 1;
  OBJECTS[X] := ROOM;
  WRITE ('DROPPED.',CR);
  IF ROOM = 1 THEN
    IF (INROOM(RING)) AND(INROOM(STATUE)) AND(INROOM(CROWN)) THEN
      ROOM := 0; (* FINISHED QUEST! *)
END;


PROCEDURE DESTROY (X : INTEGER);
BEGIN
  IF CARRYING(X) THEN
    HOLDING := HOLDING - 1;
  OBJECTS[X] := 0
END;


PROCEDURE OK;
BEGIN
  WRITE (CR,CR,'OK.',CR)
END;


PROCEDURE TAKE;
VAR I : INTEGER;
BEGIN
  IF WRD[2] = 'ALL' THEN
    FOR I := 0 TO MAXOBJ DO
      IF INROOM(I) THEN
      BEGIN
        WRITE (DESCRIBEOBJECT(I),':  ');
        PICKUP(I)
      END ELSE
  ELSE
    IF GETOBJECT (NOTCARRIED) THEN
      PICKUP (OBJ)
END;


PROCEDURE DROP;
VAR I : INTEGER;
BEGIN
  IF WRD[2] = 'ALL' THEN
    FOR I := 0 TO MAXOBJ DO
      IF CARRYING(I) THEN
        BEGIN
          WRITE (DESCRIBEOBJECT(I),': ');
          DROPIT(I)
        END ELSE
  ELSE
  IF GETOBJECT (CARRIED) THEN
    DROPIT (OBJ)
END;


PROCEDURE INSPECT;
BEGIN
  IF GETOBJECT (NEARBY) THEN
    CASE OBJ OF
      ROD, RING, STATUE :
        WRITE ('MAGIC SEEMS TO ',
               'EMANATE FROM THE ',SAYWORD(2),' ...',CR);
      BUN: WRITE ('IT LOOTS TASTY!',CR)
    ELSE
      WRITE ('YOU SEE NOTHING SPECIAL',CR)
    END
END;


PROCEDURE LOOK;
BEGIN
  IF WRD[2] = '' THEN
    OLDROOM := 0
  ELSE
    INSPECT
END;


PROCEDURE CRAZY;
BEGIN
  CASE TURNS MOD 4 OF
    0 : WRITE ('DON''T BE RIDICULOUS!',CR);
    1 : WRITE ('NICE TRY.', CR);
    2 : WRITE ('I WOULDN''T!',CR);
    3 : WRITE ('THAT''S A *VERY* SILLY IDEA!',CR)
  END
END;

PROCEDURE DONTUNDERSTAND;
BEGIN
  CASE TURNS MOD 4 OF
    0 : WRITE ('WHAT?',CR);
    1 : WRITE ('PARDON?',CR);
    2 : WRITE ('I DON''T UNDERSTAND THAT!',CR);
    3 : WRITE ('EH?',CR)
  END
END;

(* Function that keep the 3 first letter of a string
   complete with space if length is < 3              *)
FUNCTION NORMALIZE_STR( S : STRING) : STRING;
VAR  I : INTEGER ;
VAR  NORM : STRING;
BEGIN
  NORM := '';

  FOR I :=1 TO LENGH_NORM DO
  BEGIN
    IF I <= LENGTH(S) THEN
      NORM := NORM + S[I]
    ELSE
      NORM := NORM + ' '
  END;
  NORMALIZE_STR := NORM
END;


PROCEDURE GETWORD (X : INTEGER);
BEGIN
  WRD[X] := '';
  WHILE LINE[PTR] = ' ' DO
    PTR := PTR + 1;
  STARTWORD[X] := PTR;
  WHILE (LINE[PTR] <> ' ') AND (PTR <= LENGTH(LINE)) DO
  BEGIN
    WRD[X] := WRD[X] + LINE[PTR];
    PTR := PTR + 1
  END;
  ENDWORD[X] := PTR - 1;

  IF WRD[X] <> '' THEN
    WRD[X] := NORMALIZE_STR(WRD[X]);
END;


PROCEDURE GETLINE;
VAR I : INTEGER;
BEGIN
  WRITE (CR);
  REPEAT
    WRITE('> ');
    LINE :='';
    READLN(LINE);
    PTR := 1;

    FOR I := 1 TO MAXWORDS DO
      GETWORD (I);

    WHILE (LINE[PTR] = ' ') AND (PTR <= LENGTH(LINE)) DO
      PTR := PTR + 1;
    IF PTR < LENGTH(LINE) THEN
      BEGIN
        WRD[1] := '';
        WRITE (CR,'PLEASE USE NO MORE ','THAN ',MAXWORDS,' WORDS',CR,CR)
      END
  UNTIL WRD[1] <> '';

END;


PROCEDURE INSTRUCTIONS;
BEGIN
  WRITE (
'YOUR QUEST IS TO EXPLORE THE CAVE OF',CR,
'THE EVIL UR-LORD, AND BRING BACK TO',CR,
'THE EDGE OF THE CLIFF THE FOLLOWING',CR,
'VALUABLES:',CR,CR,
' 1. THE WHITE GOLD RING;',CR,
' 2. THE SACRED SILVER STATUE;',CR,
' 3. THE JEWELLED CROWN OF THE UR-LORD.',CR,CR,CR,
'BE CAREFUL ....',CR,CR,CR)
END;

PROCEDURE DESCRIBEROOM;
VAR I : INTEGER;
BEGIN
  IF (ROOM > 4) AND (NOT HERE(LAMP)) THEN
    WRITE ('IT''S TOO DARK TO SEE!',CR)
  ELSE
  BEGIN
    WRITE ('YOU ARE ');
  CASE ROOM OF

1:
WRITE ('AT A PLATEAU NEAR A CLIFF.',CR,
'A ROCKY PATH LEADS SOUTH.',CR);

2:
WRITE ('ON A ROCKY PATH LEADING',CR,
'NORTH AND CURVING TO THE EAST. THERE',CR,
'IS A SLIGHT BREEZE.',CR);

3:
WRITE ('AT THE ENTRANCE TO A DARK',CR,
'CAVE. A ROCKY PATH TO THE WEST',CR,
'CURVES NORTH.',CR);

4:
WRITE ('JUST INSIDE A DARK CAVE.',CR,
'LIGHT COMES FROM AN ENTRANCE TO THE',CR,
'WEST. THERE IS A DANK, MOULDY SMELL.',CR,
'A TUNNEL LEADS SOUTH.',CR);

5:
WRITE ('IN A LOW NORTH/SOUTH TUNNEL.',CR);

6:
WRITE ('IN AN OVAL CAVERN WITH AN',CR,
'EXIT TO THE NORTH. THERE IS A',CR,
'FORBIDDING STONE STAIRCASE LEADING',CR,
'DOWN.',CR);

7:
WRITE ('IN A HIGH, SQUARE CAVE WITH',CR,
'WALLS OF FROZEN ICE. THERE ARE',CR,
'PASSAGES IN MANY DIRECTIONS, AND',CR,
'A STAIRWAY LEADING UP.',CR);

8:
WRITE ('IN A TRIANGULAR SIDE-CHAMBER.',CR);

9:
WRITE ('IN A MUSTY-SMELLING ALCOVE.',CR);

10:
WRITE ('IN A EERIE CHAMBER - SMALL',CR,
'SQUEALING SOUNDS COME FROM THE',CR,
'WALLS.',CR);

11:
WRITE ('PASSING THROUGH AN ENORMOUS',CR,
'CAVE WITH A DOUBLE PILLAR OF GREEN',CR,
'STONE DOWN THE CENTRE. A BIG ARCH',CR,
'LEADS NORTH AND DANK TUNNELS',CR,
'LEADS FROM THE SOUTHEAST AND',CR,
'SOUTHWEST CORNERS.',CR);

12:
WRITE ('CROUCHED IN A MALODOUROUS',CR,
'TUNNEL. THE ONLY EXIT IS THE',CR,'WAY YOU CAME.',CR);

13:
WRITE ('A ROOM WHICH APPEARS TO',CR,
'ONLY HAVE AN EXIT IN THE NORTHWEST',CR,
'CORNER. HOWEVER YOU GET THE',CR,
'IMPRESSION THAT OTHERS HAVE',CR,
'SOMEHOW TRAVELLED ONWARDS THROUGH',CR,
'THIS ROOM - THE EXACT METHOD THEY',CR,
'USED IS NOT APPARENT.',CR);

14:
WRITE ('A SECRET ROOM REACHED ONLY',CR,
'BY MAGIC MEANS. A HIGH PASSAGE',CR,
'EXITS TO THE NORTHEAST.',CR);

15:
WRITE ('A DEPRESSING OCTAGONAL ROOM.',CR,
'EERIE PASSAGES LEAD NORTH AND',CR,
'SOUTHWEST.',CR);

16:
WRITE ('AN ENORMOUS MISTY CAVERN -',CR,
'THE ROOF IS SO HIGH THAT MIST',CR,
'OBSCURES IT.',CR,
'PASSAGES LEAD NORTH AND SOUTH.',CR);

17:
WRITE ('A TINY BOX-SHAPED ROOM. A',CR,
'DOOR LEADS SOUTH AND STAIRS LEAD',CR,
'DOWN.',CR);

18:
WRITE ('A BIZZARE ROOM WITH A SMELL',CR,
'OF CHLORINE. A PATH LEADS NORTH AND',CR,
'STAIRS LEAD UP.',CR);

19:
WRITE ('A STEAMY CHAMBER WITH WARM',CR,
'WALLS. FOOTSTEPS IN THE DUST SEEM',CR,
'TO LEAD WEST, AND COME FROM THE',CR,
'SOUTH.',CR);

20:
WRITE ('A LARGE ROOM, LITTERED WITH',CR,
'ALABASTER SLABS. DOORS LEAD EAST',CR,
'AND WEST.',CR);

21:
WRITE ('THE THRONE ROOM OF THE EVIL',CR,
'UR-LORD! A LOW DOOR LEADS EAST.',CR)

END; (* OF CASE *)

  FOR I := 0 TO MAXOBJ DO
    IF INROOM(I) THEN
      WRITE (CR,'THERE IS A ', DESCRIBEOBJECT(I),' HERE!',CR)
  END;
  OLDROOM := ROOM
END;


PROCEDURE EAT;
BEGIN
  IF GETOBJECT(NEARBY) THEN
    IF OBJ = BUN THEN
    BEGIN
      WRITE ('THANKS! YOU WERE RATHER HUNGRY!',CR);
      DESTROY(BUN)
    END
    ELSE
      CRAZY
END;


PROCEDURE FORCE;
BEGIN
  WRITE ('AN INVISIBLE FORCE PREVENTS YOU FROM',CR,'PASSING.',CR)
END;


PROCEDURE NOWAY;
BEGIN
   WRITE ('YOU CANNOT GO THAT WAY.',CR)
END;


PROCEDURE NORTH;
BEGIN
  CASE ROOM OF
    1  : CRAZY;
    2  : ROOM := 1;
    5  : ROOM := 4;
    6  : ROOM := 5;
    7  : ROOM := 9;
    11 : ROOM := 7;
    15 : ROOM := 16;
    16 : IF CARRYING(RING) THEN
           FORCE
         ELSE
           ROOM := 17;
    18 : IF CARRYING(STATUE) THEN
           ROOM := 19
         ELSE
           FORCE
  ELSE NOWAY END
END;


PROCEDURE SOUTH;
BEGIN
  CASE ROOM OF
    1  : ROOM := 2;
    4  : ROOM := 5;
    5  : ROOM := 6;
    9  : ROOM := 7;
    7  : ROOM := 11;
    16 : ROOM := 15;
    17 : ROOM := 16;
    19 : IF CARRYING(STATUE) THEN
           ROOM := 18
         ELSE
           FORCE
  ELSE NOWAY END
END;


PROCEDURE EAST;
BEGIN
  CASE ROOM OF
    2  : ROOM := 3;
    3  : ROOM := 4;
    7  : ROOM := 10;
    8  : ROOM := 7;
    20 : ROOM := 19;
    21 : ROOM := 20
  ELSE NOWAY END
END;


PROCEDURE WEST;
BEGIN
  CASE ROOM OF
    1  : CRAZY;
    3  : ROOM := 2;
    4  : ROOM := 3;
    10 : ROOM := 7;
    7  : ROOM := 8;
    19 : ROOM := 20;
    20 : ROOM := 21
  ELSE NOWAY END
END;


PROCEDURE UP;
BEGIN
  CASE ROOM OF
    7  : ROOM := 6;
    18 : ROOM := 17
  ELSE NOWAY END
END;


PROCEDURE DOWN;
BEGIN
  CASE ROOM OF
    6  : ROOM := 7;
    17 : ROOM := 18;
  ELSE NOWAY END
END;


PROCEDURE NORTHEAST;
BEGIN
  CASE ROOM OF
    12  : ROOM := 11;
    14  : ROOM := 15
  ELSE NOWAY END
END;


PROCEDURE NORTHWEST;
BEGIN
  CASE ROOM OF
    13  : ROOM := 11
  ELSE NOWAY END
END;

PROCEDURE SOUTHEAST;
BEGIN
  CASE ROOM OF
    11  : ROOM := 13
  ELSE NOWAY END
END;


PROCEDURE SOUTHWEST;
BEGIN
  CASE ROOM OF
    11  : ROOM := 12;
    15  : ROOM := 14
  ELSE NOWAY END
END;

PROCEDURE GOIN;
BEGIN
  CASE ROOM OF
    3  : ROOM := 4
  ELSE NOWAY END
END;


PROCEDURE GOOUT;
BEGIN
  CASE ROOM OF
    4  : ROOM := 3
  ELSE NOWAY END
END;


PROCEDURE WAVE;
BEGIN
  IF GETOBJECT(CARRIED) THEN
    IF OBJ = ROD THEN
    BEGIN
      CASE ROOM OF
        13: ROOM := 14;
        14: ROOM := 13
      ELSE
        WRITE ('NOTHING HAPPENS HERE.',CR)
      END
    END
    ELSE
      WRITE ('WAVING THE ',SAYWORD(1),' IS NOT VERY REWARDING',CR);

  IF ROOM <> OLDROOM THEN
    WRITE ('THERE IS A BLINDING FLASH ','OF LIGHT.',CR,'A LOUD ','BURPING NOISE, AND YOU ',CR,'SUDDENLY FIND ...',CR,CR);
END;


PROCEDURE GIVESCORE;
BEGIN
  SCORE := 0;
  IF OBJECTS[STATUE] = 1 THEN
    SCORE := SCORE + 100;
  IF OBJECTS[RING] = 1 THEN
    SCORE := SCORE + 100;
  IF OBJECTS[CROWN] = 1 THEN
    SCORE := SCORE + 100;
  IF CARRYING(STATUE) THEN
    SCORE := SCORE + 10;
  IF CARRYING(RING) THEN
    SCORE := SCORE + 10;
  IF CARRYING(CROWN) THEN
    SCORE := SCORE + 10;
  WRITE (CR,'YOUR SCORE IS ',SCORE,' POINTS, IN ',TURNS,' TURNS.',CR)
END;


PROCEDURE QUIT;
VAR REPLY: CHAR;
BEGIN
  GIVESCORE;
  WRITE (CR,'DO YOU WANT TO QUIT NOW? Y/N ');
  READ (REPLY);
  IF REPLY <> 'Y' THEN
   OK
  ELSE
   ROOM := 0
END;


PROCEDURE INVENTORY;
VAR I, COUNT : INTEGER;
BEGIN
  COUNT :=0;
  FOR I := 0 TO MAXOBJ DO
    IF CARRYING(I) THEN
    BEGIN
      IF COUNT = 0 THEN
        WRITE ('YOU ARE CARRYING:',CR);
      COUNT := COUNT + 1;
      WRITE (' ',DESCRIBEOBJECT(I),CR)
    END;
  IF COUNT = 0 THEN
    WRITE ('YOU AREN''T CARRYING ANYTHING!',CR)
END;


PROCEDURE VERB;
VAR I : INTEGER;
BEGIN
  WRITE (CR);
  I := 1;
  IF (WRD[I] = 'GO') OR (WRD[I] = 'RUN') OR (WRD[I] = 'NAL') OR (WRD[I] = 'MOD') OR (WRD[I] = 'GRA') THEN
  BEGIN
    IF WRD[2] = '' THEN
    BEGIN
      WRITE (SAYWORD(I),' WHERE?',CR);
      I := 0
    END
	ELSE
      I := 2
  END;

  IF I <> 0 THEN

    IF (WRD[I]='QUI') OR (WRD[I]='Q  ') THEN
	  QUIT
	ELSE IF WRD[I] = 'EAT' THEN
	  EAT
	ELSE IF (WRD[I]='NOR') OR (WRD[I]='N  ') THEN
	  NORTH
	ELSE IF (WRD[I]='SOU') OR (WRD[I]='S  ') THEN
	  SOUTH
	ELSE IF (WRD[I]='EAS') OR (WRD[I]='E  ') THEN
	  EAST
	ELSE IF (WRD[I]='WES') OR (WRD[I]='W  ') THEN
	  WEST
	ELSE IF WRD[I] = 'NE ' THEN
	  NORTHEAST
	ELSE IF WRD[I] = 'NW ' THEN
	  NORTHWEST
	ELSE IF WRD[I] = 'SE ' THEN
	  SOUTHEAST
	ELSE IF WRD[I] = 'SW ' THEN
	  SOUTHWEST
	ELSE IF (WRD[I]='UP ') OR (WRD[I]='U  ') THEN
      UP
	ELSE IF (WRD[I]='DOW') OR (WRD[I]='D  ') THEN
	  DOWN
    ELSE IF WRD[I] = 'IN ' THEN
	  GOIN
	ELSE IF WRD[I] = 'OUT' THEN
	  GOOUT
	ELSE IF (WRD[I]='TAK') OR (WRD[I]='T  ') OR (WRD[I]='GET') OR (WRD[I]='PIC') THEN
	  TAKE
	ELSE IF (WRD[I]='DRO') OR (WRD[I]='PUT') OR (WRD[I]='PLA') OR (WRD[I]='THR') THEN
	  DROP
	ELSE IF WRD[I] = 'SCO' THEN
	  GIVESCORE
    ELSE IF (WRD[I]='INV') OR (WRD[I]='I  ') THEN
      INVENTORY
    ELSE IF (WRD[I]='LOO') OR (WRD[I]='L  ') THEN
	  LOOK
	ELSE IF WRD[I] = 'WAV' THEN
	  WAVE
	ELSE IF WRD[I] = 'INS' THEN
	  INSPECT
	ELSE
	  DONTUNDERSTAND
	
END;


PROCEDURE INITIALIZE;
VAR I : INTEGER;
BEGIN
  WRITE (HOME);
  ROOM := 3;
  OLDROOM := 0;
  SCORE := 0;
  HOLDING := 0;
  TURNS := 0;
  FOR I := 0 TO MAXOBJ DO
    OBJECTS[I] := 0;
    
  OBJECTS[LAMP] := 1;
  OBJECTS[BUN] := 0;
  OBJECTS[ROD] := 9;
  OBJECTS[RING] := 13;
  OBJECTS[STATUE] := 12;
  OBJECTS[CROWN] := 21;
END;


(* ------------------------------
   PROGRAM STARTS HERE
   ------------------------------ *)
BEGIN
  INITIALIZE;
  INSTRUCTIONS;
  REPEAT
    TURNS := TURNS + 1;
    IF ROOM <> OLDROOM THEN
      DESCRIBEROOM;
    GETLINE;
    VERB;
  UNTIL ROOM = 0;

  WRITE (HOME);
  GIVESCORE;
  IF SCORE > 300 THEN
    WRITE(CR,CR,'CONGRATULATIONS!!',CR,CR,'YOU HAVE COMPLETED YOUR QUEST!',CR,CR)
END.
