name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: secret-orb

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: cargo test --verbose

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install cargo-deb
        run: cargo install cargo-deb
      
      - name: Build release binary
        run: cargo build --release --verbose
      
      - name: Create binary package
        run: |
          mkdir -p packages
          cp target/release/secret-orb packages/${{ env.BINARY_NAME }}
          tar -czf ${{ env.BINARY_NAME }}-linux-x64.tar.gz -C packages ${{ env.BINARY_NAME }}
      
      - name: Build .deb package
        run: cargo deb
      
      - name: Find and rename .deb file
        run: |
          DEB_FILE=$(find target/debian -name "*.deb" | head -1)
          cp "$DEB_FILE" ${{ env.BINARY_NAME }}-linux-x64.deb
      
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary-linux-x64
          path: ${{ env.BINARY_NAME }}-linux-x64.tar.gz
      
      - name: Upload .deb artifact  
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ${{ env.BINARY_NAME }}-linux-x64.deb

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      
      - name: Create Release (tags only)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *linux-x64.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload artifacts for main branch
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: latest-build
          path: |
            *linux-x64.*
